// tests/setup/catalog-src.ts — the seeded SOURCE database for tier-1
// catalog tests (cat-03). servo_catalog_src is created on the EXISTING
// port-5433 test container (the same server the tmpDb harness uses — no
// docker-compose diff, no new container; the pattern db-05 will apply to
// the ops sandbox). It seeds, in one schema:
//
//   payroll.payroll        — a payroll table (compensation fixture)
//   payroll.employee_id    — FK to payroll.employee (declared beats inference)
//   payroll.status         — a low-cardinality enum-like column
//   a table COMMENT and a column COMMENT
//   payroll.reference_code — unique ⇒ n_distinct = -1 after ANALYZE (the
//                            negated-ratio branch of the n_distinct trap)
//
// and RUNS ANALYZE — without it pg_stats is empty and tier 1 sees no
// statistics; the post-condition below fails naming pg_stats emptiness as
// the cause rather than letting the tests fail mysteriously.
//
// Idempotent per run: drops and recreates its own schema only.

import { PrismaClient } from "@prisma/client";
import { testDatabaseUrl, urlForDatabase } from "../helpers/tmp-db";

export const CATALOG_SRC_DB = "servo_catalog_src";

let ready: Promise<PrismaClient> | null = null;

export function catalogSrc(): Promise<PrismaClient> {
  ready ??= (async () => {
    const withLimit = (url: string) =>
    url.includes("connection_limit") ? url : url + (url.includes("?") ? "&" : "?") + "connection_limit=2";
    const admin = new PrismaClient({ datasourceUrl: withLimit(testDatabaseUrl()) });
    try {
      await admin.$executeRawUnsafe(`CREATE DATABASE ${CATALOG_SRC_DB}`);
    } catch (err) {
      if (!/already exists/i.test(String(err))) throw err;
      // Recreate deterministically: this is fixture data on a throwaway
      // test server, never a real source.
      await admin.$executeRawUnsafe(`DROP DATABASE ${CATALOG_SRC_DB} WITH (FORCE)`);
      await admin.$executeRawUnsafe(`CREATE DATABASE ${CATALOG_SRC_DB}`);
    } finally {
      await admin.$disconnect();
    }

    const src = new PrismaClient({
      datasourceUrl: withLimit(urlForDatabase(CATALOG_SRC_DB)),
    });
    await src.$executeRawUnsafe(`CREATE SCHEMA payroll`);
    await src.$executeRawUnsafe(`
      CREATE TABLE payroll.employee (
        employee_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        full_name text NOT NULL,
        reference_code text NOT NULL UNIQUE,
        hire_date date NOT NULL
      )`);
    await src.$executeRawUnsafe(`
      CREATE TABLE payroll.payroll (
        payroll_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        employee_id integer NOT NULL REFERENCES payroll.employee (employee_id),
        status text NOT NULL,
        net_pay numeric(12,2) NOT NULL,
        paid_on date NOT NULL
      )`);
    await src.$executeRawUnsafe(
      `COMMENT ON TABLE payroll.payroll IS 'One row per employee per pay period'`,
    );
    await src.$executeRawUnsafe(
      `COMMENT ON COLUMN payroll.payroll.net_pay IS 'Net compensation after withholdings'`,
    );
    // Seed enough rows that ANALYZE produces real statistics: statuses
    // repeat (low-cardinality), reference codes are unique (-1 ratio).
    await src.$executeRawUnsafe(`
      INSERT INTO payroll.employee (full_name, reference_code, hire_date)
      SELECT 'Employee ' || g, 'EMP-' || lpad(g::text, 6, '0'), DATE '2020-01-01' + (g % 1825)
        FROM generate_series(1, 200) g`);
    await src.$executeRawUnsafe(`
      INSERT INTO payroll.payroll (employee_id, status, net_pay, paid_on)
      SELECT 1 + (g % 200),
             (ARRAY ['ACTIVE','SUSPENDED','CLOSED'])[1 + g % 3],
             1200 + (g % 900) + 0.5,
             DATE '2025-01-01' + (g % 180)
        FROM generate_series(1, 600) g`);

    await src.$executeRawUnsafe(`ANALYZE payroll.employee`);
    await src.$executeRawUnsafe(`ANALYZE payroll.payroll`);

    // Post-condition: pg_stats must hold rows for both tables — if the
    // ANALYZE above ever stops running, say so instead of letting tier 1
    // see empty statistics.
    const stats = await src.$queryRawUnsafe<{ n: number }[]>(
      `SELECT COUNT(*)::int AS n FROM pg_stats
        WHERE schemaname = 'payroll' AND tablename IN ('employee', 'payroll')`,
    );
    if ((stats[0]?.n ?? 0) < 8) {
      throw new Error(
        `pg_stats is empty for the catalog source (found ${stats[0]?.n ?? 0} rows for payroll.*) — ` +
          "the ANALYZE step did not take effect; tier-1 statistics would read as absent. " +
          "This is a setup failure, not a classifier failure.",
      );
    }
    return src;
  })();
  return ready;
}

/** Dispose the shared client (vitest closes workers; the database itself
 *  lives on the throwaway test server and is recreated per process). */
export async function disposeCatalogSrc(): Promise<void> {
  if (ready) {
    const client = await ready;
    await client.$disconnect();
    ready = null;
  }
}
